### ISSUE TITLE
Configure 2i2c ohw hub for OHW-espanol 2024 events

### ISSUE THREAD

**Issue by emiliom** [oceanhackweek/Hub-Management#6]
### Notes

- The GH organization for the OHW-espanol events since November 2022 is https://github.com/orgs/Intercoonecta. The program website (in Spanish) is https://intercoonecta.github.io
- The first event will be October 15-18, 2024. It'll be an "intermediate workshop" (taller intermedio) focused on mid-level tutorials

### Tasks

- [X] Create EVENT issue at https://github.com/2i2c-org/infrastructure. **See [#4883](https://github.com/2i2c-org/infrastructure/issues/4883)**
- GH Team management (https://github.com/orgs/Intercoonecta/teams) and 2i2c hub updates to [config/clusters/2i2c/ohw.values.yaml](https://github.com/2i2c-org/infrastructure/blob/main/config/clusters/2i2c/ohw.values.yaml#L78)
  - [x] Create [ohwes24-organizers](https://github.com/orgs/Intercoonecta/teams/ohwes24-organizers)
  - [x] Populate `ohwes24-organizers`
  - [x] Create [ohwes24-mentor-helper-presenter](https://github.com/orgs/Intercoonecta/teams/ohwes24-mentor-helper-presenter)
  - [x] Populate `ohwes24-mentor-helper-presenter`
  - [x] Create [ohwes24-participants-tallerintermed](https://github.com/orgs/Intercoonecta/teams/ohwes24-participants-tallerintermed)
  - [x] Collect github handles for all participants
  - [x] Populate `ohwes24-participants-tallerintermed`
  - [x] Create [ohwes24-participants-hackaton](https://github.com/orgs/Intercoonecta/teams/ohwes24-participants-hackweek)
  - [x] Populate `ohwes24-participants-hackaton`
  - [x] Add these new `ohw24es` teams to `ohw.values.yaml`. https://github.com/2i2c-org/infrastructure/pull/4892
  - [x] Remove the two `oceanhackweek:ohw24-participants-*` teams from `ohw.values.yaml`
  - [ ] Remove other `oceanhackweek:ohw24-*` teams, too? Maybe keep just `oceanhackweek:ohw24-organizers`?
 - Update the [hub Admin page](https://oceanhackweek.2i2c.cloud/hub/admin) to add instructors and project mentors to list of people allowed to copy files to `shared-readwrite` directory
   - [x] Taller intermedio
   - [x] ~~Hackweek (it'll be the same people as in Taller intermedio, so no changes needed)~~
- [x] Add myself to the list of administrators in `config/clusters/2i2c/ohw.values.yaml`. https://github.com/2i2c-org/infrastructure/pull/4892
- Updates to hub login page, [config/clusters/2i2c/ohw.values.yaml](https://github.com/2i2c-org/infrastructure/blob/main/config/clusters/2i2c/ohw.values.yaml)
  - [x] Switch to OHWes logo image. https://github.com/2i2c-org/infrastructure/pull/4938
  - [x] Replace funder, links. Second try, this time with CSIC, https://www.csic.es/es, since they, not AECID, are the ones funding the hub. ~~https://github.com/2i2c-org/infrastructure/pull/4938~~
  - [x] Replace current text with text in Spanish. See https://github.com/2i2c-org/default-hub-homepage/pull/33
  - [x] Create text in English. See https://github.com/2i2c-org/default-hub-homepage/pull/34
- [x] Updates to Server image selection page. https://github.com/2i2c-org/infrastructure/pull/4938
- Updates to kernel images
  - This is done through https://github.com/oceanhackweek/jupyter-image. See current event issue, https://github.com/Intercoonecta/tutoriales/issues/10. For guidance and reference, see https://github.com/oceanhackweek/Hub-Management/issues/4, https://github.com/2i2c-org/infrastructure/pull/2233/files, https://github.com/Intercoonecta/tutoriales/issues/1
  - [x] Python. https://github.com/oceanhackweek/jupyter-image/pull/91, https://github.com/2i2c-org/infrastructure/pull/4938, and smaller follow-on PR's
  - [x] R. https://github.com/oceanhackweek/jupyter-image/pull/91, https://github.com/2i2c-org/infrastructure/pull/4938, and smaller follow-on PR's

**Comment by emiliom** [comment]
First set of changes to the Python and R images were done in https://github.com/oceanhackweek/jupyter-image/pull/91. Then, the request to 2i2c to update the hub is in https://github.com/2i2c-org/infrastructure/pull/4938

Once a `oceanhackweek/jupyter-image/` PR is merged, the new image tags will be at https://github.com/oceanhackweek/jupyter-image/pkgs/container/python and https://github.com/oceanhackweek/jupyter-image/pkgs/container/r

**Comment by emiliom** [comment]
When updating the R conda lock file (using `make r-lock`), `conda-lock` must be already available. **I created a conda environment with just `conda-lock`, for this purpose.**

https://github.com/oceanhackweek/jupyter-image/issues/42 discussed the creation of conda lock files.  But it's an old issue, so some of it may be out of date.

**Comment by emiliom** [comment]
**TODO.**  In login (landing page):
- [x] Fix the error with the closing `<strong>` tag
- [x] Translate the header phrase "The 2i2c JupyterHub for ...", https://github.com/2i2c-org/default-hub-homepage/blob/2i2c-ohw/templates/login.html#L20
- [x] Try rearranging so the Spanish and English text are side by side, to make better use of space
- [x] Add link and  mention of OHW in Spanish text
- [x] Add link and mention of OHW-spanish in English text, and link to OHW

I've addressed these changes in PR https://github.com/2i2c-org/default-hub-homepage/pull/34

**Comment by emiliom** [comment]
A 2i2c issue has been created for the next (and final) event: https://github.com/2i2c-org/infrastructure/issues/5052

Also, discussion for possible improvements to R environment management: https://github.com/oceanhackweek/jupyter-image/issues/90

**Comment by emiliom** [comment]
PR https://github.com/oceanhackweek/jupyter-image/pull/97 involved substantial upgrades to the R image. The discussions there are worth referring back to.

**Comment by emiliom** [comment]
The events for 2024 have ended.
